version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - node
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  redis:
    image: redis
    expose: 6379
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
  node:
    build:
      context: ./app